# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""The model artefact (spec §9): ``MODEL`` is the JSON source of truth,
``model/ownership.fga`` is its rendered DSL, and ``REQUIRED`` is what
``fga show-model --check`` diffs a store's actual model against."""

from __future__ import annotations

import copy
import os

import pytest
from superset_ownership import cli_fga, fga
from superset_ownership.model import MODEL, model_signature, render_dsl, REQUIRED

_OWNERSHIP_FGA_PATH = os.path.join(
    os.path.dirname(__file__), "..", "model", "ownership.fga"
)


def test_render_dsl_matches_the_committed_dsl_file():
    """`model/ownership.fga` is generated by `render_dsl(MODEL)`; the file on
    disk carries a license header the render function does not produce, so
    the comparison starts at the DSL body's own first line."""
    with open(_OWNERSHIP_FGA_PATH, encoding="utf-8") as f:
        text = f.read()
    body = text[text.index("model\n") :]
    assert body == render_dsl(MODEL)


def test_render_dsl_is_deterministic():
    assert render_dsl(MODEL) == render_dsl(copy.deepcopy(MODEL))


def test_required_is_a_subset_of_what_model_declares():
    declared = {
        type_def["type"]: set((type_def.get("relations") or {}).keys())
        for type_def in MODEL["type_definitions"]
    }
    for type_name, relations in REQUIRED.items():
        assert type_name in declared, (
            f"REQUIRED names a type MODEL does not declare: {type_name}"
        )
        missing = set(relations) - declared[type_name]
        assert not missing, (
            f"REQUIRED.{type_name} names relations MODEL does not declare: {missing}"
        )


def test_required_matches_the_spec_table():
    assert REQUIRED == {
        "user": [],
        "tenant": ["member"],
        "group": ["member", "tenant"],
        "dashboard": ["owner", "editor", "viewer", "tenant"],
        "chart": ["owner", "editor", "viewer", "tenant"],
    }


def test_render_dsl_expresses_the_or_chain_and_directly_related_types():
    text = render_dsl(MODEL)
    assert "define editor: [user, group#member] or owner" in text
    assert "define viewer: [user, group#member] or editor" in text
    assert "define tenant: [tenant#member]" in text
    assert "define member: [user, group#member]" in text
    assert "type user\n\n" in text, "user has no relations block"


# ----------------------------------------------------------------- model_signature (S6)


def _openfga_echo(model: dict, model_id: str = "01ECHO0000000000000000000") -> dict:
    """What OpenFGA's own GET actually returns for a model this module
    wrote: schema_version and type_definitions round-trip, but every
    userset ref grows a `"condition": ""`, every relations/metadata block
    grows a `"module": ""` and `"source_info": null`, and a type with no
    relations (`user`) comes back with an explicit `"relations": {},
    "metadata": null` instead of the bare `{"type": "user"}` this module
    sends. `install-model`'s idempotency check has to see through all of
    that or it can never recognise its own model coming back."""
    out = copy.deepcopy(model)
    out["id"] = model_id
    for type_def in out["type_definitions"]:
        if not type_def.get("relations"):
            type_def["relations"] = {}
            type_def["metadata"] = None
            continue
        metadata = type_def.setdefault("metadata", {})
        metadata["module"] = ""
        metadata["source_info"] = None
        rel_meta = metadata.setdefault("relations", {})
        for relation_name in type_def["relations"]:
            entry = rel_meta.setdefault(relation_name, {})
            entry["module"] = ""
            entry["source_info"] = None
            for ref in entry.get("directly_related_user_types", []):
                ref["condition"] = ""
    return out


def test_model_signature_matches_across_an_openfga_style_round_trip():
    """The exact bug S6 has to avoid: naive dict equality between MODEL and
    what a real store echoes back never matches, because OpenFGA adds
    fields this module never sent."""
    echoed = _openfga_echo(MODEL)
    assert echoed != MODEL, (
        "the fixture must actually add the store's noise, or this proves nothing"
    )
    assert model_signature(echoed) == model_signature(MODEL)


def test_model_signature_detects_a_genuinely_different_model():
    stale = _model_missing_group_tenant()
    assert model_signature(stale) != model_signature(MODEL)


def test_model_signature_is_order_independent():
    """N8: relations can come back in a different order than MODEL defines
    them in (the store's own, alphabetical); the signature must not care."""
    reordered = copy.deepcopy(MODEL)
    for type_def in reordered["type_definitions"]:
        if type_def.get("relations"):
            type_def["relations"] = dict(reversed(list(type_def["relations"].items())))
    assert model_signature(reordered) == model_signature(MODEL)


def test_model_signature_ignores_the_userset_refs_own_order():
    reordered = copy.deepcopy(MODEL)
    for type_def in reordered["type_definitions"]:
        for entry in (type_def.get("metadata", {}) or {}).get("relations", {}).values():
            entry["directly_related_user_types"] = list(
                reversed(entry.get("directly_related_user_types", []))
            )
    assert model_signature(reordered) == model_signature(MODEL)


# ------------------------------------------------------ R2-2: wildcard/condition/schema


def _add_dashboard_viewer_ref(model: dict, ref: dict) -> dict:
    model = copy.deepcopy(model)
    for type_def in model["type_definitions"]:
        if type_def["type"] == "dashboard":
            type_def["metadata"]["relations"]["viewer"][
                "directly_related_user_types"
            ].append(ref)
    return model


def test_model_signature_detects_a_wildcard_grant():
    """R2-2: a store model that also grants `user:*` (public, wildcard
    access) on viewer must NOT compare equal to MODEL -- before this fix,
    `install-model` would have called a wildcard-widened store "already
    current" and left the widening in place."""
    widened = _add_dashboard_viewer_ref(MODEL, {"type": "user", "wildcard": {}})
    assert model_signature(widened) != model_signature(MODEL)


def test_model_signature_detects_a_condition():
    conditioned = _add_dashboard_viewer_ref(
        MODEL, {"type": "user", "condition": "only_weekdays"}
    )
    assert model_signature(conditioned) != model_signature(MODEL)


def test_model_signature_ignores_the_stores_own_empty_condition_noise():
    """The store's own added `"condition": ""` on every OTHER (real) ref --
    not a wildcard, not an actual condition -- must still compare equal;
    only a non-empty condition is a real difference."""
    echoed = _openfga_echo(MODEL)
    assert model_signature(echoed) == model_signature(MODEL)


def test_model_signature_detects_a_schema_version_change():
    older = copy.deepcopy(MODEL)
    older["schema_version"] = "1.0"
    assert model_signature(older) != model_signature(MODEL)


def test_render_dsl_renders_a_wildcard_ref():
    widened = _add_dashboard_viewer_ref(MODEL, {"type": "user", "wildcard": {}})
    assert "user:*" in render_dsl(widened)


def test_render_dsl_renders_a_condition():
    conditioned = _add_dashboard_viewer_ref(
        MODEL, {"type": "user", "condition": "only_weekdays"}
    )
    assert "with only_weekdays" in render_dsl(conditioned)


def test_render_dsl_renders_nothing_extra_for_an_unconditioned_ref():
    assert "with " not in render_dsl(MODEL)


# ------------------------------------------------------------------- show-model --check


def _model_missing_group_tenant() -> dict:
    """A model shaped like a store mid-rollout: every REQUIRED relation
    present except `group.tenant`, the one addition this spec makes."""
    model = copy.deepcopy(MODEL)
    for type_def in model["type_definitions"]:
        if type_def["type"] == "group":
            del type_def["relations"]["tenant"]
            del type_def["metadata"]["relations"]["tenant"]
    return model


def test_missing_relations_reports_group_tenant_on_a_pre_rollout_model():
    missing = cli_fga._missing_relations(_model_missing_group_tenant())
    assert missing == ["group.tenant"]


def test_missing_relations_is_empty_for_a_complete_model():
    assert cli_fga._missing_relations(MODEL) == []


def test_missing_relations_reports_every_gap_on_a_bare_model():
    bare = {"schema_version": "1.1", "type_definitions": [{"type": "user"}]}
    missing = cli_fga._missing_relations(bare)
    assert "tenant.member" in missing
    assert "group.member" in missing
    assert "group.tenant" in missing
    assert "dashboard.owner" in missing
    assert "chart.viewer" in missing
    assert len(missing) == sum(len(v) for v in REQUIRED.values())


# ------------------------------------------------------- install-model / show-model CLI


class _Store:
    """A fake OpenFGA store answering only the authorization-models routes."""

    def __init__(
        self,
        model_json: dict | None = None,
        written_id: str = "01NEWMODEL0000000000000000",
    ):
        self.model_json = model_json
        self.written_id = written_id
        self.write_calls: list[dict] = []

    def post(self, url, json=None, headers=None, timeout=None):
        import requests

        if url.endswith("/authorization-models"):
            self.write_calls.append(json)
            r = requests.Response()
            r.status_code = 200
            r._content = f'{{"authorization_model_id": "{self.written_id}"}}'.encode()
            return r
        raise AssertionError(f"unexpected POST {url}")

    def get(self, url, json=None, headers=None, timeout=None):
        import json as _json  # noqa: TID251 - `json` is a param name in this scope

        import requests

        r = requests.Response()
        if url.endswith("/authorization-models") and self.model_json is not None:
            r.status_code = 200
            r._content = _json.dumps(
                {"authorization_models": [{**self.model_json, "id": "latest"}]}
            ).encode()
        elif "/authorization-models/" in url and self.model_json is not None:
            r.status_code = 200
            r._content = _json.dumps(
                {
                    "authorization_model": {
                        **self.model_json,
                        "id": url.rsplit("/", 1)[-1],
                    }
                }
            ).encode()
        else:
            r.status_code = 404
            r._content = b'{"code": "not_found"}'
        return r


def test_install_model_writes_the_model_json_and_returns_its_id(monkeypatch):
    store = _Store()
    monkeypatch.setattr(fga.requests, "post", store.post)
    monkeypatch.setattr(fga.requests, "get", store.get)
    model_id = fga.write_model(MODEL)
    assert model_id == store.written_id
    assert store.write_calls == [MODEL]


def test_show_model_check_reports_missing_relations_against_a_fake_store(monkeypatch):
    store = _Store(model_json=_model_missing_group_tenant())
    monkeypatch.setattr(fga.requests, "post", store.post)
    monkeypatch.setattr(fga.requests, "get", store.get)
    fetched = fga.get_model()
    missing = cli_fga._missing_relations(fetched)
    assert missing == ["group.tenant"]


def test_show_model_check_reports_nothing_missing_against_a_complete_fake_store(
    monkeypatch,
):
    store = _Store(model_json=MODEL)
    monkeypatch.setattr(fga.requests, "post", store.post)
    monkeypatch.setattr(fga.requests, "get", store.get)
    fetched = fga.get_model()
    assert cli_fga._missing_relations(fetched) == []


def test_get_model_raises_store_rejected_when_the_store_has_no_models(monkeypatch):
    store = _Store(model_json=None)
    monkeypatch.setattr(fga.requests, "post", store.post)
    monkeypatch.setattr(fga.requests, "get", store.get)
    with pytest.raises(fga.StoreRejected):
        fga.get_model()
